// User
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const USER_FAIL = 'USER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FALL = 'LOGIN_FALL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

// Errors
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

// Student
export const STUDENT_LOADING = 'STUDENT_LOADING';
export const STUDENTS_LOADED = 'STUDENTS_LOADED';
export const STUDENT_LOADED = 'STUDENT_LOADED';
export const STUDENT_CREATED = 'STUDENT_CREATED';
export const STUDENT_UPDATED = 'STUDENT_UPDATED';
export const STUDENT_DELETED = 'STUDENT_DELETED';
export const STUDENT_FAIL = 'STUDENT_FAIL';

// Subject
export const SUBJECT_LOADING = 'SUBJECT_LOADING';
export const SUBJECTS_LOADED = 'SUBJECTS_LOADED';
export const SUBJECT_LOADED = 'SUBJECT_LOADED';
export const SUBJECT_CREATED = 'SUBJECT_CREATED';
export const SUBJECT_UPDATED = 'SUBJECT_UPDATED';
export const SUBJECT_DELETED = 'SUBJECT_DELETED';
export const SUBJECT_FAIL = 'SUBJECT_FAIL';
